server:
  port: 8081

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.notificationservice.event.OrderCreatedEvent
        spring.json.use.type.headers: false
