server:
  port: 8080

spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        acks: all
        spring.json.add.type.headers: false